create database MYWEB
use MYWEB
CREATE TABLE MENU(
	Parent_id nvarchar(10) not null,
	Id nvarchar(10) NOT NULL,
	Menucontent nvarchar(50),
)
CREATE TABLE SUBMENU1(
	Id nvarchar(10) NOT NULL,
	 Submenu nvarchar(50)NOT NULL,
)
CREATE TABLE SUBMENU2(
	Id nvarchar(10) NOT NULL,
	 Submenu nvarchar(50) NOT NULL,
)
ALTER TABLE MENU ADD CONSTRAINT P_MN PRIMARY KEY(Id)
ALTER TABLE SUBMENU1 ADD CONSTRAINT P_SMN1 PRIMARY KEY(Submenu)
ALTER TABLE SUBMENU2 ADD CONSTRAINT P_SMN2 PRIMARY KEY(Submenu)
ALTER TABLE SUBMENU1 ADD CONSTRAINT F_SUB1 FOREIGN KEY(Id) REFERENCES MENU(Id)
ALTER TABLE SUBMENU2 ADD CONSTRAINT F_SUB2 FOREIGN KEY(Id) REFERENCES MENU(Id)


INSERT INTO MENU VALUES('0','1','THOI TRANG NAM')
INSERT INTO MENU VALUES('0','2','THOI TRANG NU')
INSERT INTO MENU VALUES('0','3','ME VA BE')
INSERT INTO MENU VALUES('0','4','THOI TRANG CAP')
INSERT INTO MENU VALUES('0','5','DONG HO')
select * from MENU
select * from SUBMENU1

INSERT INTO SUBMENU1 VALUES('1','QUAN JEEN NAM')
INSERT INTO SUBMENU1 VALUES('1','AO THUN NAM')
INSERT INTO SUBMENU1 VALUES('1','AO KHOAC NAM')
INSERT INTO SUBMENU1 VALUES('1','QUAN KAKI NAM')
INSERT INTO SUBMENU1 VALUES('1','DONG HO NAM')

INSERT INTO SUBMENU2 VALUES('2','QUAN JEEN NAM')
INSERT INTO SUBMENU2 VALUES('2','AO THUN NAM')
INSERT INTO SUBMENU2 VALUES('2','AO KHOAC NAM')
INSERT INTO SUBMENU2 VALUES('2','QUAN KAKI NAM')
INSERT INTO SUBMENU2 VALUES('2','DONG HO NAM')

